# Generated by Django 2.2.7 on 2020-01-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ass_id', models.CharField(max_length=50)),
                ('fac_id', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
                ('date_ass', models.DateField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assessment',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('fac_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('hour', models.BinaryField()),
            ],
            options={
                'db_table': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('fac_id', models.IntegerField()),
                ('room', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Class',
            },
        ),
        migrations.CreateModel(
            name='faculties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(blank=True, max_length=20, null=True)),
                ('j_date', models.DateField(max_length=20)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('batch', models.CharField(blank=True, max_length=10, null=True)),
                ('blood', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'faculty_details',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('leave_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('date_app', models.DateField()),
                ('session', models.CharField(max_length=20)),
                ('fac_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'leave',
            },
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('l_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=50)),
                ('fac_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('hour', models.BinaryField()),
            ],
            options={
                'db_table': 'Result',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_no', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('roll', models.IntegerField()),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('course', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('ad_date', models.DateField()),
                ('f_name', models.CharField(blank=True, max_length=50, null=True)),
                ('m_name', models.CharField(blank=True, max_length=50, null=True)),
                ('blood', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('p_mobile', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('religion', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'student_details',
            },
        ),
    ]
